# Generated by Django 2.0.4 on 2018-11-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVIDAD_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muycerca', models.IntegerField()),
                ('cerca', models.IntegerField()),
                ('lejos', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.SESION')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVIDAD_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mano_izquierda', models.IntegerField()),
                ('mano_derecha', models.IntegerField()),
                ('manos_arriba', models.IntegerField()),
                ('manos_abajo', models.IntegerField()),
                ('izquierda', models.IntegerField()),
                ('derecha', models.IntegerField()),
                ('adelante', models.IntegerField()),
                ('atras', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.SESION')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVIDAD_C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabeza', models.IntegerField()),
                ('boca', models.IntegerField()),
                ('hombros', models.IntegerField()),
                ('pechos', models.IntegerField()),
                ('manos', models.IntegerField()),
                ('vagina', models.IntegerField()),
                ('gluteos', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.SESION')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVIDAD_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amarillo', models.IntegerField()),
                ('azul', models.IntegerField()),
                ('fucsia', models.IntegerField()),
                ('rojo', models.IntegerField()),
                ('turquesa', models.IntegerField()),
                ('verde', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.SESION')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVIDAD_E',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alegria', models.IntegerField()),
                ('tristeza', models.IntegerField()),
                ('miedo', models.IntegerField()),
                ('sorpresa', models.IntegerField()),
                ('enfado', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.SESION')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVIDAD_F',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silencio', models.IntegerField()),
                ('lugar', models.IntegerField()),
                ('saludo', models.IntegerField()),
                ('gracias', models.IntegerField()),
                ('porfavor', models.IntegerField()),
                ('perdon', models.IntegerField()),
                ('disculpe', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.SESION')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVIDAD_G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplausos', models.IntegerField()),
                ('zapateos', models.IntegerField()),
                ('golpes', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.SESION')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVIDAD_H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cero', models.IntegerField()),
                ('uno', models.IntegerField()),
                ('dos', models.IntegerField()),
                ('tres', models.IntegerField()),
                ('cuatro', models.IntegerField()),
                ('cinco', models.IntegerField()),
                ('seis', models.IntegerField()),
                ('siete', models.IntegerField()),
                ('ocho', models.IntegerField()),
                ('nueve', models.IntegerField()),
                ('diez', models.IntegerField()),
                ('once', models.IntegerField()),
                ('doce', models.IntegerField()),
                ('trece', models.IntegerField()),
                ('catorce', models.IntegerField()),
                ('quince', models.IntegerField()),
                ('dieciseis', models.IntegerField()),
                ('diecisiete', models.IntegerField()),
                ('dieciocho', models.IntegerField()),
                ('diecinueve', models.IntegerField()),
                ('veinte', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.SESION')),
            ],
        ),
    ]
